# Generated by Django 4.2.16 on 2024-10-02 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("equipment", "0004_rename_progress_equipment_progress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monster", "0005_monster_max_health"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("distance", models.IntegerField()),
                ("pace", models.DurationField(blank=True, null=True)),
                ("created_on", models.TimeField(auto_now_add=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlock_runs",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recover_runs",
                        to="monster.monster",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
