# Generated by Django 4.2.16 on 2024-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.IntegerField(
                        choices=[(0, "Armour"), (1, "Weapon")], default=0
                    ),
                ),
                ("benefit_health", models.IntegerField()),
                ("benefit_damage", models.IntegerField()),
                ("distance_needed", models.IntegerField()),
                ("equipment_svg", models.TextField()),
                ("created_on", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
