# Generated by Django 4.2.16 on 2024-10-01 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("monster", "0004_monster_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked", models.BooleanField(default=False)),
                ("Progress", models.IntegerField()),
                ("created_on", models.TimeField(auto_now_add=True)),
                (
                    "monster",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipped",
                        to="monster.monster",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_type",
                        to="equipment.equipmenttype",
                    ),
                ),
            ],
        ),
    ]
