# Generated by Django 4.2.16 on 2024-10-02 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0003_alter_equipment_progress_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="Progress",
            new_name="progress",
        ),
    ]
