# Generated by Django 4.2.16 on 2024-10-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0004_rename_progress_equipment_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipments",
                to="equipment.equipmenttype",
            ),
        ),
    ]
