# Generated by Django 4.2.16 on 2024-09-26 13:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonsterType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("base_max_health", models.IntegerField()),
                ("base_damage", models.IntegerField()),
                (
                    "type_image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("created_on", models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
