# Generated by Django 4.2.16 on 2024-09-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monster", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monstertype",
            name="type_image",
        ),
        migrations.AddField(
            model_name="monstertype",
            name="type_svg",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
