# Generated by Django 4.2.16 on 2024-10-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monster", "0004_monster_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="max_health",
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
