# Generated by Django 4.2.16 on 2024-10-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monster", "0006_alter_monster_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="monster",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
