# Generated by Django 4.2.16 on 2024-10-06 08:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monster", "0007_monster_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="color",
            field=colorfield.fields.ColorField(
                default="#f60000", image_field=None, max_length=25, samples=None
            ),
        ),
    ]
